FROM mysql:8.0

# Копируем файлы конфигурации
COPY ./slave/slave.cnf /etc/mysql/conf.d/my.cnf
COPY ./slave/slave.sql /docker-entrypoint-initdb.d/start.sql

# Переменные окружения для настройки репликации
ENV MYSQL_ROOT_PASSWORD=12345

# Запускаем сервисы
CMD ["mysqld"]
